-- user
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (false,'2001-11-01','11 Ben Nghe','admin123@gmail.com','admin1','admin123','admin','0938472726',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2002-10-21','08 Nguyen Binh Khiem, Quang Ngai','quangtin1@gmail.com','manager1','manager123','manager','0395115975',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2000-10-21','18 Hoang Hoa Tham, Thu Duc ','manager123@gmail.com','manager2','manager12345','manager','0395115976',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2003-10-23','2123 Le Viet Luong','thien010502@gmail.com','thien','123456a~','customer','0938472725',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2002-02-02','DakLak','thiencm02@gmail.com','thiencm02Aa','Tian1a)','manager','0938472720',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2002-04-07','04 Le Van Viet','cuong@gmail.com','cuong3Que','chrissTrinha123^','customer','0938472721',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (false,'2000-09-02','113 Quang Trung, Da Nang','vanh khuyen43@gmail.com','Vanhkh43','Bon3@!.','customer','0395117976',1);
-- blog
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES (1,'Thiết Kế Phòng Khách Tivi Treo Tường Hiện Đại Đẹp Không Góc Chết', 'Chiều cao và khoảng cách lắp đặt tivi có ảnh hưởng rất lớn tới trải nghiệm xem của người dùng. Theo các chuyên gia, chiều cao lý tưởng để lắp tivi là 0,6-1,2m so với sàn nhà. Ở độ cao này, mọi người có thể dễ dàng quan sát màn hình mà không bị cổ căng hay mỏi mắt. Bên cạnh đó, khoảng cách từ tivi đến vị trí ngồi của người xem nên là 2-2,5m. Nếu đặt quá xa, hình ảnh sẽ nhỏ và mờ, ngược lại nếu đặt quá gần cũng khiến mắt dễ mệt mỏi, thậm chí có hại cho thị lực. Ngoài ra, tùy thuộc vào kích cỡ màn hình và diện tích phòng khách mà bạn có thể chọn chiều cao và khoảng cách phù hợp. Ví dụ đối với màn hình 32 inch trở xuống thì khoảng cách lý tưởng là 2m. Còn với màn hình lớn hơn thì tốt nhất là 2,5-3m mới đảm bảo chất lượng hình ảnh tốt nhất. Vị trí lắp tivi có tầm quan trọng không kém gì chiều cao và khoảng cách. Bạn nên tránh những vị trí ánh sáng mặt trời hoặc đèn chiếu trực tiếp vào màn hình. Lý do là vì ánh sáng tự nhiên hay nhân tạo sẽ làm lóa màn hình, giảm độ tương phản và chất lượng video. Thay vào đó, bạn nên chọn tường treo tivi không có cửa sổ để lắp đặt. Hoặc nếu bắt buộc, hãy trang bị màn che, rèm cửa sổ để hạn chế tối đa tình trạng chiếu sáng trực tiếp. Bạn nên bố trí đồ nội thất hợp lý để không gian hài hòa, cân đối và thẩm mỹ. Ví dụ, có thể kết hợp tivi với kệ treo tường, giấy dán tường để tạo hiệu ứng. Hoặc kết hợp với hệ thống đèn chiếu sáng hoặc đèn trang trí xung quanh tivi cũng rất đẹp mắt. Đặc biệt, bố trí ghế sofa đối diện với tivi để xem các chương trình một cách thoải mái nhất. Kệ tivi vừa là nơi để đặt tivi, vừa là điểm nhấn thẩm mỹ. Do đó, việc lựa chọn kiểu dáng kệ phù hợp là vô cùng cần thiết. Theo các chuyên gia nội thất, bạn nên mẫu có thiết kế đơn giản, thanh nhã, hài hòa với tổng thể không gian phòng khách. Khung kệ có thể làm bằng gỗ tự nhiên, gỗ công nghiệp hoặc kim loại, tùy theo phong cách chung. Ngoài tính thẩm mỹ, kệ cần chắc chắn để đỡ được trọng lượng của tivi. Đặc biệt, tránh các họa tiết rườm rà, chi tiết phức tạp để không làm rối mắt, ảnh hưởng đến việc xem tivi. Mẫu tivi treo tường theo phong cách hiện đại: Theo phong cách hiện đại, thiết kế tivi treo tường sẽ tập trung vào sự tinh tế và công nghệ. Tổng thể phòng khách toát lên vẻ đẹp hiện đại, trang nhã và khác biệt nhờ sự kết hợp hài hòa giữa nội thất cùng công nghệ. Mẫu tivi treo tường theo phong cách tối giản: Mẫu tivi treo tường theo phong cách tối giản toát lên vẻ đẹp nhã nhặn và sự nhẹ nhàng thanh thoát trong từng đường nét thiết kế. Chủ yếu nhấn mạnh vào công năng giải trí, không gian xung quanh được sắp xếp gọn gàng, ngăn nắp, loại bỏ những vật dụng rườm rà. Kết hợp kệ treo tường, giấy dán tường: Việc kết hợp kệ tivi gỗ đơn giản với lớp giấy dán tường có hoa văn tinh tế sẽ mang lại vẻ đẹp hiện đại, ấn tượng cho không gian. Đây là lựa chọn tuyệt vời để thiết kế phòng khách tivi đẹp không góc chết. Kết hợp đèn: Đây là cách bố trí tivi treo tường giúp tạo điểm nhấn cho không gian phòng khách. Dùng đèn LED, đèn thả hay âm tường với ánh sáng vàng ấm áp sẽ giúp không gian phòng khách trở nên lung linh và ấn tượng hơn. Ánh sáng vừa đủ cùng vị trí đèn được cân nhắc kỹ lưỡng sẽ đem lại hiệu ứng thị giác tuyệt vời, thu hút mọi ánh nhìn. Kết hợp tủ rượu: Việc kết hợp khéo léo giữa tủ rượu và tivi treo tường chính là bí quyết giúp không gian phòng khách thêm phần sang trọng, tinh tế. Cách bố trí này vừa tiết kiệm diện tích lại tạo không gian giải trí ấn tượng, lý tưởng để thư giãn sau những giờ làm việc căng thẳng. Kệ tivi treo trên gỗ giả đá: Kệ tivi được làm từ gỗ giả đá sang trọng sẽ mang đến vẻ đẹp hiện đại và đẳng cấp cho phòng khách. Đảm bảo trở thành điểm nhấn ấn tượng cho không gian decor, thể hiện gu thẩm mỹ của gia chủ. Kết hợp tường hiệu ứng 3D: Với vẻ đẹp độc đáo và ấn tượng, tường 3D kết hợp tivi là lựa chọn hoàn hảo cho những gia chủ yêu thích sự mới lạ và muốn tạo điểm nhấn mới lạ cho phòng khách của mình. Kết hợp tường trơn: Đây là mẫu thiết kế tối giản, chiếc tivi treo tường là điểm nhấn duy nhất của căn phòng, thể hiện công năng giải trí chính của không gian.',2,'2023-02-05',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES (1,'11+ Mẫu Phòng Bếp Nhà Ống', ' Khi nhắc đến đặc điểm của không gian, bạn sẽ liên tưởng đến những yếu tố về diện tích, phong cách thiết kế, ánh sáng, nội thất. Dựa theo những tiêu chí này, phòng bếp nhà ống 5m sẽ có những điểm chung như: Kích thước, diện tích phòng bếp hạn chế với đặc điểm là hẹp ngang và kéo dài đúng theo dáng của mảnh đất. Vị trí: đối với nhà ống, đa số ngôi nhà bố trí theo chiều dọc với thứ tự là: nơi phòng khách – nhà vệ sinh – phòng ăn – nhà bếp. Do đó, phòng bếp thường được đặt ở cuối ngôi nhà. Ánh sáng: do không gian được đặt ở cuối nhà, xung quanh là những căn cao tầng khác nên không gian thường có ít ánh sáng tự nhiên, mỗi khi sử dụng nhà bếp đều phải bật đèn chiếu sáng. Phong cách thiết kế hiện đại và tân cổ điển là chủ yếu. Căn bếp tập trung vào sự gọn gàng, tối giản nhưng vẫn thẩm mỹ và ấm áp. Nội thất phòng bếp thường có đồ điện gia dụng, tủ treo tường, tủ bàn bếp nấu ăn, bồn rửa, bếp nấu sắp xếp theo hình chữ L, chữ U, có thể có thêm đảo bếp song song với bếp nấu. Nhà bếp thường có khả năng thông gió hạn chế, khi nấu nướng, mùi dễ bị bay ra không gian ngoài phòng khách và lên tầng cao. Dù phòng bếp của nhà ống có nhiều hạn chế về diện tích, đặc biệt là chiều rộng nhưng bạn vẫn có thể tạo ra không gian tiện nghi, ấm áp và thuận tiện cho các hoạt động được diễn ra tại đây. Những cách thiết kế mà Huy Hoàng gợi ý đến bạn: Tận dụng tối đa diện tích của căn phòng bằng cách sử dụng tủ bếp chữ I, chữ L. Những chiếc tủ có thể đặt vừa khít ở vị trí góc và che được phần diện tích tối này. Tạo hiệu ứng rộng rãi cho không gian: sử dụng cửa sổ, giếng trời lấy sáng tự nhiên, giấy dán tường màu trắng hoặc màu trung tính thiên về sắc sáng, đèn màu trắng hoặc trắng vàng nhẹ. Tạo thông thoáng, khử mùi cho nhà bếp bằng cách lắp đặt quạt hút mùi, máy hút mùi. Sắp xếp đồ dùng trật tự, lấy đồ ở đâu thì cất gọn tại vị trí đó sau khi dùng xong. Lựa chọn nội thất được làm từ chất liệu cao cấp, có thời gian sử dụng lâu bền. Điều này vừa giúp bạn không cần sửa chữa, thay thế, vừa mang đến hiệu quả kinh tế trong lâu dài. Phong cách phòng bếp nhà ống 5m cần có sự liên kết và thống nhất với các không gian khác là phòng khách và phòng ăn. Đồng thời, nhà bếp có diện tích hạn chế nên bạn không nên sử dụng những kiểu có nhiều chi tiết nhỏ, họa tiết tỉ mỉ và kích thước quá lớn. Những kiểu nội thất thường được sử dụng gồm: Phong cách hiện đại với một số đặc trưng như: Ưu tiên công năng sử dụng và có đa chức năng. Ví dụ, các ngăn tủ bếp có kích thước đa dạng, thiết kế thông minh để đựng được bát, đũa, rổ, xoong nồi và đồ khô. Các sản phẩm có màu sắc tươi sáng, tự nhiên, đường nét và họa tiết đơn giản. Phòng bếp trẻ trung và năng động với tông màu tươi sáng, nội thất được làm từ chất liệu bền bỉ và hiện đại như gỗ công nghiệp, nhựa cứng, đá, đệm da. Phòng bếp phong cách tối giản sử dụng những món đồ nội thất theo thói quen ăn uống của gia đình. Tất cả những dụng cụ ít sử dụng đều được cất gọn gàng ở tủ để không gian bếp luôn thoáng và ít đồ trưng bày nhất có thể. Phong cách nhiệt đới với tông màu chính là xanh, vàng, cam cùng chất liệu tre nứa, đồng hồ treo tường, tranh phong cảnh và cây xanh nhỏ.',2,'2023-02-05',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES (1,'30+ Mẫu Thiết Kế Phòng Khách Có Cầu Thang Dọc Không Thể Bỏ Lỡ', 'Sử dụng thảm kết hợp trang trí phòng khách có cầu thang dọc giúp tạo sự an toàn cho các thành viên trong gia đình. Dạng thảm sử dụng cần bám chặt vào sàn, chỉ bị rơi ra khi có tác động ngoại lực. Ngoài ra, các bạn có thể thỏa sức lựa chọn các tấm thảm phù hợp hoặc đổi mới không gian ngồi nhà. Ánh sáng là một yếu tố đặc biệt quan trọng trong thiết kế nhà ở. Ánh sáng không chỉ giúp căn nhà trở nên sáng hơn với hiệu ứng thị giác, mà còn có ý nghĩa phong thuỷ. Gia chủ nên thiết kế hệ thống đèn cầu thang với lượng ánh sáng vừa đủ, không quá chói. Hãy ưu tiên lựa chọn các loại đèn led với lượng sáng thích hợp với không gian cầu thang của gia đình. Một mẹo thú vị trong trang trí nội thất chính là treo tranh ảnh lên lối vào cầu thang phòng khách. Việc này sẽ giúp lấp đầy các không gian trống trong phòng khách, cùng với đó cũng sẽ giúp căn nhà thêm phần ấn tượng dù chỉ với thiết kế vô cùng đơn giản. Thiết kế nội thất hiện tại hầu hết đều chú trọng đến yếu tố tích hợp nhiều tính năng. Cầu thang dọc là một chi tiết rất thích hợp để tận dụng để làm giá sách, kệ tủ,… Điều này giúp gia tăng giá trị thẩm mỹ cho căn nhà, giúp ngôi nhà của bạn thêm phần thông thoáng và rộng rãi. Cầu thang là một thiết kế quan trọng trong mỗi căn nhà nên rất được gia chủ chú trọng. Dưới đây là các vật liệu thường gặp nhất trong thiết kế, mỗi chất liệu đều sở hữu những đặc tính riêng biệt. Sắt là nguyên liệu vô cùng phổ biến và được yêu thích trong thiết kế cầu thang do giá thành rẻ và độ bền rất cao. Bên cạnh đó, cầu thang sắt cũng có đa dạng thiết kế cùng với hoa văn tinh xảo, phủ bên ngoài là lớp sơn phù hợp với nội thất căn nhà. Tuy nhiên, sắt có một nhược điểm đó chính là dễ bị oxi hoá sau thời gian dài sử dụng, cần được bảo hành thường xuyên. Inox có độ bóng cao nên giúp không gian tăng độ chiếu sáng. Đây là vật liệu hiện đại, có nhiều ưu thế hơn so với sắt nhờ trọng lượng thấp, không bị han gỉ và ăn mòn bởi điều kiện tự nhiên. Vì thế, dùng inox để thiết kế cầu thang dọc là lựa chọn thông minh, giúp gia chủ không tốn nhiều chi phí bảo dưỡng. Kính là vật liệu thiết kế cầu thang độc đáo, giúp không gian như được tăng lên và tạo sự tráng lệ cho căn nhà. Kính sử dụng làm cầu thang dọc sẽ là kính cường lực với khả năng chịu lực và chịu nhiệt cực cao, đảm bảo an toàn cho người sử dụng. Thường cầu thang kính sẽ được kết hợp với tay vịn gỗ hoặc kim loại để không gian thêm hài hoà. Tuy nhiên giá thành của cầu thang kính lại tương đối cao.',2,'2024-02-20',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES (2,'Quy Trình Thiết Kế Nhà Trọn Gói',' Quy trình thiết kế nhà trọn gói. Bước 1: Khi nhận được thông tin có nhu cầu thiết kế nhà trọn gói của khách hàng, đơn vị tư vấn sơ bộ cho khách hàng qua điện thoại về nhu cầu công năng, phong cách kiến trúc, quy trình thiết kế nhà. Bước 2: Khi khách hàng thống nhất sử dụng dịch vụ của đơn vị, đơn vị thi công sẽ gửi hợp đồng thiết kế để làm cơ sở thiết kế sơ bộ (Thiết kế sơ bộ bao gồm mặt bằng công năng các tầng). Bước 3: Khi khách hàng thống nhất với phương án thiết kế sơ bộ, 2 bên tiến hành Ký hợp đồng thiết kế tại vị trí xây dựng. Bước 4: Khi hồ sơ kỹ thuật thi công hoàn thành 100% khối lượng, khách hàng thanh toán giá trị hợp đồng, đơn vị thi công sẽ gửi khách hàng hồ sơ bản vẽ thi công qua đường chuyển fax nhanh, hoặc khách hàng có thể nhận hồ sơ trực tiếp tại văn phòng. Hồ sơ thiết kế nhà trọn gói – phần kết cấu: – Phần móng: Trong thiết kế phần móng sẽ bao gồm bảng vẽ mặt bằng móng,  mặt cắt chi tiết móng, giằng móng, giằng tường, mặt bằng giằng tường, tường móng, chi tiết bể phốt bể nước.. – Phần cột: Trong thiết kế phần cột sẽ bao gồm bảng vẽ thể hiện kích thước cột cao, rộng, thép cột, thép thang, mặt bằng kết cấu thang, cao độ thang, chiếu nghỉ…. – Phần dầm: Khi thiết kế phần dầm sẽ thể hiện định vị dầm tầng, mặt cắt dọc cắt ngang dầm, thống kê thép dầm… – Phần sàn: Trong này sẽ thể hiện định vị sàn tầng, cốt thép sàn tầng, chiều dầy,…. – Phần lanh tô: Thể hiện định vị lanh tô, bảng thống kê cốt thép lanh tô, chi tiết lanh tô, … Hồ sơ thiết kế nhà trọn gói – phần điện: Mặt bằng chiếu sáng các tầng. Thể hiện vị trí các đèn trần, đèn tường, đi dây, công tắc chiếu sáng tới các bóng… Mặt bằng ổ cắm. Thể hiện vị trí các ổ cắm, cao độ ổ cắm, chủng loại ổ cắm… Mặt bằng đường internet, truyền hình cáp, điện thoại. Thể hiện hướng đi , vị trí các ổ cắm, chủng loại cáp…. Mặt bằng chống sét. Thể hiện định vị kim thu sét, cọc chống sét, hướng đi cáp chống sét, vật tư vật liệu…. Các chi tiết cấu tạo. Thể hiện quy cách lắp đặt, Thống kê vật tư vật liệu điện. Hồ sơ thiết kế nhà trọn gói – phần nước: Mặt bằng cấp thoát nước tổng thể. Thể hiện hướng thoát nước các đường ống ngoài nhà, đường kính ống, các lộ di chuyển ống… Mặt bằng cấp nước các tầng. Thể hiện cấp nước lên téc, cấp nước vào nhà, cấp nước vào thiết bị Mặt bằng thoát nước các tầng. Thể hiện thoát nước mưa, thoát nước thiết bị vệ sinh, thoát nước hố ga… Chi tiết cấp nước vệ sinh. Thể hiện triển khai chi tiết cấp nước từ đường ống đến các thiết bị trong nhà vệ sinh… Chi tiết thoát nước vệ sinh. Thể hiện triển khai chi tiết thoát nước các thiết bị trong nhà vệ sinh đến đường ống đứng.. Sơ đồ cấp thoát nước không gian. thể hiện mô phỏng không gian các đường cấp thoát nước, dễ hình dung, trực quan…',2,'2023-02-05',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES (2,'TOP 25 Mẫu Nhà Phố Có Garage Đẹp Mới Nhất', 'Vị trí của gara cần được chọn sao cho thuận tiện cho việc vào ra của xe ô tô. Gara nên nằm ở mặt tiền hoặc mặt hậu của nhà, cách ranh lộ giới ít nhất 3m và có độ dốc không quá 15% so với mặt đường. Nếu bạn xây dựng gara ở tầng hầm hay bán hầm, bạn cần chú ý đến chiều cao trần và chiều rộng lối vào của gara. Chiều cao trần gara tối thiểu là 2m2, chiều rộng lối vào tối thiểu là 3m. Một số vị trí phổ biến để bố trí gara trong nhà phố là: Gara ở tầng trệt: Đây là vị trí thông dụng nhất, phù hợp với nhà diện tích rộng và giúp tiết kiệm chi phí xây dựng cũng như di chuyển xe dễ dàng. Tuy nhiên kiểu thiết kế này cũng có nhược điểm là chiếm diện tích sinh hoạt của gia đình. Gara ở tầng hầm: Là thiết kế lý tưởng cho nhà phố khi diện tích đất hạn chế hoặc khi muốn tạo ra không gian sinh hoạt rộng rãi ở tầng trệt. Gara ở tầng hầm giúp bảo vệ xe tốt hơn, không ảnh hưởng đến kiến trúc mặt tiền của ngôi nhà. Nhưng chi phí xây dựng cao và cần đảm bảo hệ thống thoát nước, thông gió và chiếu sáng hiệu quả. Gara ở tầng bán hầm: Là vị trí lai giữa gara ở tầng trệt và gara ở tầng hầm. Ưu điểm là tiết kiệm chi phí xây dựng, không chiếm diện tích sinh hoạt. Tuy nhiên, gara ở tầng bán hầm cũng cần chú ý độ cao từ mặt sàn đến mặt đường và không quá 1.2 mét để đảm bảo an toàn. Diện tích của gara sẽ phụ thuộc vào loại xe và số lượng xe mà bạn sử dụng. Theo tiêu chuẩn quy định, nếu để xe ô tô 4 chỗ, diện tích tối thiểu của gara thường là 3.5m x 5m hoặc 3.5m x 5.5m (đối với xe ô tô thân dài). Nếu dùng để lưu trữ xe ô tô 7 chỗ, diện tích tối thiểu yêu cầu là 4m x 6m. Trong trường hợp chứa nhiều xe ô tô trong gara thì còn phải tính toán sao cho có đủ khoảng cách an toàn giữa các xe và giữa xe với các bức tường. Khi xây dựng gara, bạn cần chú ý đến kết cấu của nó và phải đảm bảo sao cho bền chắc, an toàn cho xe cũng như người sử dụng.  Một số yếu tố cần lưu ý khi thiết kế kết cấu của gara là: Cửa gara: Là bộ phận quan trọng nên cần chọn vật liệu tốt, có khả năng chống chịu va đập, chống nước, chống rỉ sét và chống cháy. Các gia chủ có thể chọn các loại cửa cuốn, cửa kéo hay cửa tự động để tiện lợi cho việc mở đóng. Đặc biệt, kích thước rộng hơn kích thước xe ít nhất 0.5m2, để dễ dàng cho việc vào ra của xe. Sàn gara: Đây là nơi tiếp xúc trực tiếp với xe hơi do đó yêu cầu phải chịu được tải trọng lớn. Sàn gara nên được làm bằng bê tông cốt thép hoặc bê tông xi măng, có độ dày phù hợp và có độ bám dính cao để tránh trơn trượt khi xe vào ra. Ngoài ra, còn cần lưu ý đến hệ thống thoát nước và chống thấm hiệu quả để tránh ẩm mốc. Mái gara: Phần che phủ cho gara, có tác dụng bảo vệ xe khỏi các yếu tố thời tiết. Nếu gara ngoài trời thì các gia chủ có thể tham khảo thiết kế mái bằng, mái lệch, mái xanh. Hay sử dụng các vật liệu bền, nhẹ, chống cháy như tôn, nhựa, kính hoặc composite. Thiết kế gara không chỉ phải đảm bảo tính công năng và an toàn cho xe hơi mà còn phải hài hòa với kiến trúc tổng thể của ngôi nhà. Việc này đảm bảo tạo ra một không gian đẹp mắt, sang trọng và đồng bộ cho tổng thể công trình. Cụ thể: Phong cách kiến trúc: Gara nên được thiết kế theo phong cách kiến trúc của ngôi nhà. Ví dụ như hiện đại, cổ điển, tân cổ điển để có sự đồng điệu về màu sắc, hình dạng, chi tiết và vật liệu. Vị trí và kích thước: Gia chủ cần bố trí gara cho phù hợp với mặt bằng và diện tích của ngôi nhà. Không nên quá lớn hoặc quá nhỏ so với tổng thể để tránh làm mất sự cân đối, tính thẩm mỹ. Hoặc gây ảnh hưởng đến thông gió, ánh sáng của ngôi nhà. Hình ảnh và chi tiết: Các chi tiết trang trí cho gara như cột, mái hiên, lan can, đèn hoặc cây xanh cũng cần chú trọng để tạo điểm nhấn và sự liên kết với ngôi nhà. Vấn đề an toàn cháy nổ là một trong những yếu tố quan trọng khi xây dựng nhà phố có gara. Xe hơi là một nguồn nguy hiểm tiềm ẩn rủi ro cao do chứa nhiều chất dễ cháy như xăng, dầu, khí ga hoặc pin. Do đó, khi xây dựng gara bảo quản cất trữ xe ô tô, bạn cần phải tuân thủ các quy chuẩn kỹ thuật. Một số lưu ý mà gia chủ cần biết đó là: Thiết kế hệ thống thoát khí và thông gió cho gara. Đảm bảo hệ thống báo cháy tự động và phương tiện chữa cháy. Nên có biển báo ngăn cấm hút thuốc lá hoặc mang các nguồn lửa vào trong gara. Không để các vật liệu dễ cháy hoặc các dung dịch khác trong gara. Kiểm tra thường xuyên các thiết bị điện và các linh kiện của xe. Tiếng ồn khi vận hành ô tô có thể làm phiền hàng xóm hoặc các thành viên trong gia đình. Do đó, bạn nên lựa chọn các giải pháp để giảm tiếng ồn khi xây nhà phố có gara. Dưới đây là một số cách mà các gia chủ có thể tham khảo: Xây tường cách âm: Đây là một biện pháp hiệu quả để ngăn chặn tiếng ồn. Bạn có thể xây tường cách âm bằng các vật liệu hấp thụ âm hoặc vật liệu phản xạ âm.  Đặc biệt, chú ý đến độ dày nhất định để đảm bảo khả năng cách âm. Trồng cây xanh để giảm thiểu tiếng ồn: Cây xanh là một biện pháp tự nhiên và thân thiện với môi trường để giảm thiểu tiếng ồn cho gara. Chúng có tác dụng hấp thụ và phản xạ âm thanh, giúp giảm độ vang và tiếng ồn trong gara. Lắp đặt hệ thống cách âm cho xe ô tô: Bạn có thể dán các tấm chống ồn vào khoang động cơ, nắp ca-pô, gầm xe, cửa xe và các bộ phận khác để hấp thụ và triệt tiêu âm thanh từ động cơ và mặt đường. Lót sàn gỗ hoặc cao su: Đây là cách giảm tiếng ồn khi xe di chuyển, vận hành trong gara. Các loại vật liệu này có tác dụng hấp thụ và triệt tiêu âm thanh từ mặt sàn và gầm xe, giảm độ rung lắc xe.',2,'2023-02-05',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES (2,'Bật Mí Xu Hướng Thiết Kế Nội Thất Phòng Khách Hiện Đại, Sang Trọng','Với những ngôi nhà có diện tích khiêm tốn, không gian phòng khách nhỏ thì nên thiết kế nội thất phòng khách theo xu hướng tối giản, tập trung vào công năng sử dụng của các đồ dùng nội thất là lựa chọn thích hợp nhất. Tuyệt đối không trang trí các vật dụng nội thất có kích thước quá lớn, hoa văn xa hoa, lộng lẫy. Vì như vậy chỉ tạo cảm giác chật hẹp cho không gian phòng khách của gia đình bạn mà thôi. Các vật dụng nội thất đơn giản, tinh tế, màu sắc trang nhã sẽ khiến phòng khách của bạn thông thoáng hơn rất nhiều. Nếu bạn yêu thích phong cách cổ điển có thể chọn một vài món đồ decor nội thất làm điểm nhấn không gian phòng khách. Chẳng hạn như một chiếc đèn gỗ, hoa văn tinh xảo hay một bộ tranh kim loại Phong Thủy sẽ giúp phòng khách của bạn nghiêng về sắc thái hoài cổ, kết hợp với nội thất hiện đại, đáp ứng yêu cầu và sở thích của chính bạn. Một trong những xu hướng thiết kế được đánh giá và phản hồi tích cực nhất hiện nay chính là phong cách đơn giản nhưng không đơn điệu, đủ tinh tế, trang nhã, đem lại không gian sống gần gũi, hiện đai, tiện ích và quan trọng nhất là không bao giờ bị “lỗi mốt”. Phòng khách theo phong cách thiết kế này thường sử dụng các đồ dùng nội thất tối giản, chẳng hạn như sofa đơn sắc tạo cảm giác mềm mại, uyển chuyển, làm điểm nhấn thú vị của không gian phòng khách, đồng thời đáp ứng được nhu cầu sử dụng gia chủ. Đơn giản nhưng không phải đơn điệu, ngoài sofa đơn sắc, bạn có thể trang trí thêm nội thất phòng khách bằng các vật dụng nhỏ nhắn, tinh xảo, để phòng khách thêm đẹp mắt. Tất nhiên, với nhưng không gian phòng khách có diện tích eo hẹp, đừng phô bày quá nhiều đồ dùng nội thất, chỉ sử dụng những vật dụng cơ bản kèm theo một hai vật trang tí nhỏ. Chỉ bấy nhiêu thôi cũng đủ cho phòng khách của bạn trở nên đặc biệt rồi. Cuộc sống hiện đại, công nghệ phát triển, con người có xu hướng tìm về chốn thiên nhiên xanh mát để lấy lại cân bằng, năng lượng trong cuộc sống. Cho nên thiết kế nội thất phòng khách gần gũi với tự nhiên đang là xu hướng HOT nhất trong vài năm trở lại đây. Việc trang trí phòng khách với cây xanh, hoa cỏ, giúp không gian rộng thoáng, tạo cảm giác mát mẻ, dịu nhẹ, tiết kiệm điện năng cho căn nhà của bạn. Có thể nói, đây chính là ưu điểm nổi bật của xu hướng thiết kế phòng khách gần gũi với thiên nhiên, cây cỏ. Với kiểu xu hướng thiết kế này, phòng khách của bạn phải có không gian vừa hoặc rộng. Nếu không gian nhỏ, chỉ nên trang trí một đến hai chậu cây nhỏ để tiết kiệm diện tích. Nếu không gian phòng khách đủ rộng, bạn có thể đầu tư các decor trang trí gắn liền với cây xanh, vừa đẹp, vừa tạo cảm giác xanh mát, thoải mái, nhất là vào ngày hè nắng nóng. Kết hợp nhiều loại vật liệu trong cùng một không gian sẽ phác họa lên vẻ đẹp xa hoa, lộng lẫy của phòng khách gia đình bạn. Xu hướng thiết kế này phù hợp với phòng khách diện tích có không gian rộng thoáng. Với các phòng khách eo hẹp về diện tích, xu hướng này không được phù hợp cho lắm. Cho nên, bạn hãy nhớ điều kiện đầu tiên sử dụng nhiều loại vât liệu trong thiết kế không gian phòng khách là diện tích phải đủ rộng. Phong cách thiết kế kết hợp nhiều loại vật liệu này đáp ứng mọi sở thích, mong muốn và khát khao của gia chủ. Bạn có thể chọn tất tần tật các loại vật liệu, vật dụng nội thất mà bạn thích, sau đó chỉ cần phối hợp sao cho ăn ý, dung hòa nhất là được. Để làm được điều này, chọn một nhà thiết kế nội thất chuyên nghiệp là điều quan trọng nhất. Phòng khách là nơi tiếp đón khách khứa cũng là nơi sinh hoạt chung của các thành viên trong gia đình. Cho nên, phòng khách thường có diện tích lớn nhất, rộng rãi nhất, thể hiện đầy đủ nét thẩm mỹ tổng hợp của các thành viên trong nhà. Đây chính là lý do xu hướng thiết kế nội thất cho phòng khách rộng mở ngày càng được ưa chuộng. Thường thì kiểu phòng khách này nối liên tiếp với các phòng khách, người ta thường sử dụng vách ngăn gỗ, kính hoặc kệ sách để phân chia không gian. Như vậy, phong cách thiết kế này vừa tiết kiệm diện tích, vừa tạo cảm giác rộng thoáng và tiện nghi hơn rất nhiều.',2,'2023-02-05',null);

-- material type
INSERT INTO material_type(type_name, status) VALUES ('Sắt Thép',1);
INSERT INTO material_type(type_name, status) VALUES ('Cát Xây Dựng',1);
INSERT INTO material_type(type_name, status) VALUES ('Xi Măng Xây Dựng',1);
INSERT INTO material_type(type_name, status) VALUES ('Gạch Tuynel Xây Dựng',1);
INSERT INTO material_type(type_name, status) VALUES ('Gạch Ốp Nền, Tường',1);
INSERT INTO material_type(type_name, status) VALUES ('Đá Xây Dựng',1);
INSERT INTO material_type(type_name, status) VALUES ('Sơn Nước',1);
INSERT INTO material_type(type_name, status) VALUES ('Bột Trét',1);
INSERT INTO material_type(type_name, status) VALUES ('Cửa',1);
INSERT INTO material_type(type_name, status) VALUES ('Lan Can',1);
INSERT INTO material_type(type_name, status) VALUES ('Dây Điện, Dây Cáp',1);
INSERT INTO material_type(type_name, status) VALUES ('Ống Nước',1);
INSERT INTO material_type(type_name, status) VALUES ('Tôn',1);
INSERT INTO material_type(type_name, status) VALUES ('Ngói',1);
-- material
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Hòa Phát Ø6, Ø8 ',1, 11000,'Sắt Thép Hòa Phát 3','kg',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Hòa Phát Ø10 ',1, 77995,'Sắt Thép Hòa Phát', 'cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Hòa Phát Ø12 ',1, 110323,'Sắt Thép Hòa Phát', 'cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Hòa Phát Ø14 ',1, 152208,'Sắt Thép Hòa Phát 2','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Hòa Phát Ø16 ',1, 199360,'Sắt Thép Hòa Phát 2','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Việt Nhật Ø10',1, 63582,'Sắt Thép Việt Nhật',  'cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Việt Nhật Ø12',1, 73900,'Sắt Thép Việt Nhật','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Việt Nhật Ø14',1, 109900,'Sắt Thép Việt Nhật 2','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Việt Nhật Ø16',1, 150500,'Sắt Thép Việt Nhật 2','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Pomina Ø6, Ø8 ',1, 14500,'Sắt Thép Pomina','kg',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Pomina Ø10 ',1, 105773,'Sắt Thép Pomina','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Pomina Ø12 ',1, 150655,'Sắt Thép Pomina 1','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Pomina Ø14 ',1, 205322,'Sắt Thép Pomina 1','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sắt Thép Pomina Ø16 ',1, 268105,'Sắt Thép Pomina 1','cây',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cát Vàng',2, 200000, 'Cát Vàng', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cát Đen',2, 150000, 'Cát Đen', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cát Xây Tô',2, 120000, 'Cát Xây Tô', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cát San Lấp',2, 90000, 'Cát San Lấp', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cát Bê Tông',2, 250000, 'Cát Bê Tông', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng SCG',3, 101000, 'Xi Măng SCG', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng Sông Gianh',3, 95000, 'Xi Măng Sông Gianh', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng Nghi Sơn',3, 89000, 'Xi Măng Nghi Sơn', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng Hà Tiên',3, 85000, 'Xi Măng Hà Tiên', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng Hà Tiên Xây Tô',3, 76000, 'Xi Măng Hà Tiên Xây Tô', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng Vicem Hạ Long',3, 86000, 'Xi Măng Vicem Hạ Long', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng INSEE',3, 87000, 'Xi Măng INSEE', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng INSEE Xây Tô',3, 73000, 'Xi Măng INSEE Xây Tô', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Xi Măng FICO',3, 78000, 'Xi Măng FICO', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Đặc Tuynel',4, 980, 'Gạch Tuynel', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Tuynel 2 Lỗ',4, 990, 'Gạch Tuynel 2 Lỗ', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Đặc Thạch Bàn',4, 1750, 'Gạch Đặc Thạch Bàn',  'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Không Trát 2 Lỗ',4, 2900, 'Gạch Không Trát 2 Lỗ',  'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Không Trát 2 Lỗ Sẫm',4, 6200, 'Gạch Không Trát 2 Lỗ Sẫm', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Đặc Không Trát Xám',4, 4100, 'Gạch Đặc Không Trát Xám', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Đặc Không Trát Sẫm',4, 6200, 'Gạch Đặc Không Trát Sẫm', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Đặc Không Trát Khổ Lớn',4, 26500, 'Gạch Đặc Không Trát Khổ Lớn', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Không Trát 3 Lỗ',4, 5600, 'Gạch Không Trát 3 Lỗ', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch 4 Lỗ Vuông ',4, 1220, 'Gạch 4 Lỗ Vuông', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch 4 Lỗ Tròn ',4, 1320, 'Gạch 4 Lỗ Tròn','viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch 6 Lỗ Vuông ',4, 3500, 'Gạch 6 Lỗ Vuông','viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch 6 Lỗ Tròn',4, 3600, 'Gạch 6 Lỗ Tròn', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Prime _30*60_8164 ',5, 167000, 'GOT_8164', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Prime _30*60_8632 ',5, 166000, 'GOT_8632', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Prime _30*60_8165 ',5, 187000, 'GOT_8165', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Prime_30*60_9455 ',5, 160000, 'GOT_9455', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Prime _30*60_8661 ',5, 195000, 'GOT_8661', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Prime _30*60_17315 ',5, 75000, 'GOT_17315', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3616A ',5, 210000, 'GOT_3616A', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3676 ',5, 220000, 'GOT_3676', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3644A ',5, 225000, 'GOT_3644A', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3623 ',5, 145000, 'GOT_3623', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3604A ',5, 195000, 'GOT_3604A', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền Prime_30*30_9612 ',5, 140000, 'GON_9612', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền Prime_30*30_9473 ',5, 128000, 'GON_9473', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền Prime_30*30_9603 ',5, 151000, 'GON_9603', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền Prime_60*60_9669 ',5, 192000, 'GON_9669', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền Prime_60*60_17026 ',5, 181000, 'GON_17026', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền Prime_60*60_9864 ',5, 235000, 'GON_9864', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền Prime_60*60_9509 ',5, 211000, 'GON_9509', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền S_60*60_68017 ',5, 181000, 'GON_68017', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền S_60*60_68035 ',5, 284000, 'GON_68035', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền S_60*60_68030C ',5, 321000, 'GON_68030C', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Gạch Ốp Nền S_60*60_65001C ',5, 325000, 'GON_65001C', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Đá Xanh 1*2',6, 280000, 'Đá Xanh 1x2', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Đá Xanh 0*4',6, 220000, 'Đá Xanh 0x4', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Đá Xanh 4*6',6, 360000, 'Đá Xanh 4x6', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Đá Xanh 5*7',6, 390000, 'Đá Xanh 5x7', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Đá Đen 1*2',6, 260000, 'Đá Đen 1x2', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Đá Đen 4*6',6, 340000, 'Đá Đen 4x6', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Đá Mi Sàng',6, 220000, 'Đá Mi Sàn', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Đá Mi Bụi',6, 210000, 'Đá Mi Bụi', 'm3',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Maxilite 5L',7, 415000, 'Sơn Maxilite', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Maxilite 18L',7, 1405000, 'Sơn Maxilite', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Maxilite HC 5L',7, 258000, 'Sơn Maxilite HC',  'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Maxilite HC 18L',7, 878000, 'Sơn Maxilite HC', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Maxilite Smooth 5L',7, 241000, 'Sơn Maxilite Smooth', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Maxilite Smooth 18L',7, 801000, 'Sơn Maxilite Smooth', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Dulux Inspire 5L',7, 551000, 'Sơn Dulux Inspire', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Dulux Inspire 18L',7, 1874000,'Sơn Dulux Inspire', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Jotun Jotaplast',7, 851000, 'Sơn Jotun Jotaplast', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Jotun Majestic 5L',7, 873000, 'Sơn Jotun Majestic', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Jotun Majestic 15L',7, 2253000, 'Sơn Jotun Majestic', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Jotun Majestic Primer 5L',7, 483000, 'Sơn Jotun Majestic Primer', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Sơn Jotun Majestic Primer 17L',7, 1548000, 'Sơn Jotun Majestic Primer', 'thùng',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Bột Trét Homecote',8, 265000, 'BT Homecote', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Bột Trét Jotun Nội Thất',8, 230000, 'BT Jotun Nội Thất', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Bột Trét Jotun Ngoại Thất',8, 330000, 'BT Jotun Ngoại Thất', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Bột Trét Việt Mỹ Nội Thất',8, 110000, 'BT Việt Mỹ Nội Thất', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Bột Trét Việt Mỹ Ngoại Thất',8, 120000, 'BT Việt Mỹ Ngoại Thất', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Bột Trét Dulux Nội Thất',8, 310000, 'BT Dulux Nội Thất', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Bột Trét Dulux Ngoại Thất',8, 410000, 'BT Dulux Ngoại Thất', 'bao',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Nhôm Xingfa Nhập Khẩu',9, 1650000, 'Cửa Nhôm Xingfa', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Nhôm Xingfa Trong Nước',9, 1550000, 'Cửa Nhôm Xingfa', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Nhôm Việt Pháp',9, 1100000, 'Cửa Nhôm Việt Pháp', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Gỗ HDF',9, 1990000, 'Cửa Gỗ HDF', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Gỗ HDF Veneer',9, 2450000, 'Cửa Gỗ HDF Veneer', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Gỗ HDF Melaminate',9, 2100000, 'Cửa Gỗ HDF Melaminate-Laminate', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Gỗ HDF Laminate',9, 2600000, 'Cửa Gỗ HDF Melaminate-Laminate', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Gỗ Vòm MDF',9, 1600000, 'Cửa Gỗ Vòm MDF', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Gỗ Vòm MDF Veneer',9, 1750000, 'Cửa Gỗ Vòm MDF Veneer', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Gỗ Vòm MDF Melaminate',9, 1950000, 'Cửa Gỗ Vòm MDF Melaminate-Laminate', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cửa Gỗ Vòm MDF Laminate',9, 2700000, 'Cửa Gỗ Vòm MDF Melaminate-Laminate', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Kính Tempered 8mm Cường Lực',10, 510000, 'Lan Can Kính Cường Lực', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Kính Tempered 12mm Cường Lực',10, 680000, 'Lan Can Kính Cường Lực', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Sắt ',10, 550000, 'Lan Can Sắt', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Sắt Hộp',10, 850000, 'Lan Can Sắt Hộp', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Ban Công Inox201',10, 650000, 'Lan Can Ban Công Inox201', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Ban Công Inox304',10, 920000, 'Lan Can Ban Công Inox304', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Cầu Thang Inox201',10, 2200000, 'Lan Can Inox201', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Cầu Thang Inox304',10, 2700000, 'Lan Can Inox304', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Lan Can Bậc Gỗ CămXe',10, 950000, 'Lan Can Bậc Gỗ CămXe', 'm2',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Ngầm CADIVI_50',11, 46500, 'Cáp Cadivi', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Ngầm CADIVI_70',11, 63500, 'Cáp Cadivi', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Ngầm CADIVI_95',11, 81500, 'Cáp Cadivi', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Ngầm CADIVI_150',11, 118200, 'Cáp Cadivi', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Ngầm CADIVI_240',11, 169700, 'Cáp Cadivi', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Ngầm LS VINA_35',11, 30980, 'Cáp LS VINA', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Ngầm LS VINA_50',11, 82300, 'Cáp LS VINA', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Ngầm LS VINA_70',11, 136940, 'Cáp LS VINA', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Điện SINO',11, 118000, 'Cáp SINO', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Cáp Điện DAPHACO',11, 92270, 'Cáp DAPHACO', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Tiền Phong 21',12, 9600, 'Ống Nhựa Tiền Phong', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Tiền Phong 27',12, 20700, 'Ống Nhựa Tiền Phong', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Tiền Phong 34',12, 34200, 'Ống Nhựa Tiền Phong', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Bình Minh 21',12, 12600, 'Ống Nhựa Bình Minh','m',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Bình Minh 27',12, 15800, 'Ống Nhựa Bình Minh', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Bình Minh 34',12, 21200, 'Ống Nhựa Bình Minh', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Hoa Sen',12, 14600, 'Ống Nhựa Hoa Sen', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Dekko 21',12, 11495, 'Ống Nhựa Dekko', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Dekko 27',12, 14960, 'Ống Nhựa Dekko', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ống Nước Nhựa Dekko 34',12, 19495, 'Ống Nhựa Dekko', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Tôn Việt Nhật',13, 69000, 'Tôn Việt Nhật', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Tôn Đông Á',13, 93000, 'Tôn Đông Á', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Tôn Hoa Sen',13, 95000, 'Tôn Hoa Sen', 'm',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ngói Đất Nung',14, 26000, 'Ngói Đất Nung', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ngói Composite',14, 28000, 'Ngói Composite', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ngói Màu(Ngói Xi Măng)',14, 39000, 'Ngói Xi Măng', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ngói Sóng',14, 15000, 'Ngói Sóng', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ngói Phẳng',14, 19000, 'Ngói Phẳng', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ngói Thái Lan SCG',14, 20000, 'Ngói Thái Lan SCG', 'viên',1);
INSERT INTO material(material_name,material_type_id,unit_price,img_path, unit, status) VALUES ('Ngói Đồng Tâm',14, 24200, 'Ngói Đồng Tâm', 'viên',1);
-- combo building
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Thô 3',3500000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Hoàn Thiện 5',3800000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Hoàn Thiện 6',4000000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Trọn Gói 5',4300000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Trọn Gói 6',4600000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Gói Thô 2',2000000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Hoàn Thiện 3',2200000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Hoàn Thiện 4',2500000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Trọn Gói 3',2700000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Trọn Gói 4',3000000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Gói Thô 1',1500000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Hoàn Thiện 1',1700000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Hoàn Thiện 2',1900000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Trọn Gói 1',2300000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Trọn Gói 2',2500000, 2,1);

-- combo detail
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,3,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,22,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,29,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,61,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,84,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,87,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,96,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,104,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,113,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,128,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,134,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (1,141,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,2,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,21,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,48,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,66,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,79,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,90,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,97,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,109,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,114,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,125,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,134,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (2,140,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,4,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,21,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,58,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,65,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,79,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,90,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,101,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,104,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,113,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,125,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,134,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (3,140,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,2,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,20,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,50,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,66,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,82,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,86,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,102,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,111,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,114,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,131,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,134,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (4,141,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,2,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,20,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,62,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,66,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,82,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,87,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,102,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,111,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,114,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,131,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,134,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (5,141,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,6,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,23,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,29,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,55,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,77,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,89,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,92,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,106,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,117,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,125,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,133,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (6,135,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,7,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,23,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,29,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,57,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,75,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,89,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,95,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,103,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,112,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,125,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,133,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (7,136,10);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,7,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,23,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,42,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,75,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,88,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,96,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,107,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,118,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,126,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,133,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (8,137,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,8,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,22,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,48,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,84,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,87,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,97,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,107,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,118,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,129,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,133,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (9,135,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,8,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,22,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,59,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,67,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,79,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,91,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,98,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,111,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,118,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,129,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,133,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (10,135,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,11,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,28,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,29,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,47,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,80,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,85,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,94,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,105,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,120,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,122,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,132,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (11,138,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,12,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,25,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,29,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,53,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,77,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,88,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,96,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,106,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,117,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,123,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,132,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (12,139,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,12,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,25,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,29,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,53,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,77,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,89,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,96,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,106,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,117,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,124,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,133,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (13,140,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,6,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,26,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,46,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,75,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,89,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,95,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,109,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,117,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,125,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,133,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (14,141,5);

INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,6,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,15,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,26,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,30,10);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,46,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,64,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,75,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,90,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,95,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,109,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,117,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,128,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,134,1);
INSERT INTO combo_detail(combo_building_id,material_id, quantity) VALUES (15,135,5);

-- building type
INSERT INTO building_type (status, building_type_name) VALUES (true, 'biet thu');
INSERT INTO building_type (status, building_type_name) VALUES (true, 'nha pho');
INSERT INTO building_type (status, building_type_name) VALUES (true, 'nha cap 4');

-- building
INSERT INTO building (percent_price, status, building_type_id, building_name) VALUES (1.2, true, 1, 'Biet thu co');
INSERT INTO building (percent_price, status, building_type_id, building_name) VALUES (1.1, true, 1, 'Biet thu hien dai');
INSERT INTO building (percent_price, status, building_type_id, building_name) VALUES (1.0, true, 2, 'Nha pho thuong');
INSERT INTO building (percent_price, status, building_type_id, building_name) VALUES (1.05, true, 2, 'Nha pho cao cap');
INSERT INTO building (percent_price, status, building_type_id, building_name) VALUES (0.95, true, 3, 'Nha cap 4 thuong');
INSERT INTO building (percent_price, status, building_type_id, building_name) VALUES (1.0, true, 3, 'Nha cap 4 cao cap');
INSERT INTO building (percent_price, status, building_type_id, building_name) VALUES (1.05, true, 3, 'Nha cap 4 hien dai');
INSERT INTO building (percent_price, status, building_type_id, building_name) VALUES (1.1, true, 2, 'Nha pho hien dai');


-- building detail
INSERT INTO building_detail (area, check_date, finish_date, has_tunnel, numofloor, numobathroom, numobedroom, numokitchen, start_date, status, building_id) VALUES (100, null, null, false, 1, 1, 2, 1, null, 0, 5);
INSERT INTO building_detail (area, check_date, finish_date, has_tunnel, numofloor, numobathroom, numobedroom, numokitchen, start_date, status, building_id) VALUES (140, '2024-03-08', null, true, 1, 2, 2, 2, '2024-01-01', 1, 7);
INSERT INTO building_detail (area, check_date, finish_date, has_tunnel, numofloor, numobathroom, numobedroom, numokitchen, start_date, status, building_id) VALUES (300, '2023-08-04', '2024-10-11', true, 3, 3, 3, 2, '2023-06-07', 2, 3);
INSERT INTO building_detail (area, check_date, finish_date, has_tunnel, numofloor, numobathroom, numobedroom, numokitchen, start_date, status, building_id) VALUES (200, null, null, false, 1, 2, 1, 1, null, -1, 5);
INSERT INTO building_detail (area, check_date, finish_date, has_tunnel, numofloor, numobathroom, numobedroom, numokitchen, start_date, status, building_id) VALUES (400, '2022-09-03', '2023-01-02', false, 1, 3, 3, 2, '2022-07-14', 2, 2);
INSERT INTO building_detail (area, check_date, finish_date, has_tunnel, numofloor, numobathroom, numobedroom, numokitchen, start_date, status, building_id) VALUES (540, '2023-12-28', null, true, 3, 2, 4, 2, '2023-09-02', 1, 3);
INSERT INTO building_detail (area, check_date, finish_date, has_tunnel, numofloor, numobathroom, numobedroom, numokitchen, start_date, status, building_id) VALUES (170, null, null, true, 1, 2, 1, 1, '2024-02-23', 1, 6);

-- request contract
INSERT INTO request_contract (date_meet, pay_status, request_date, status, timeout_date, total_price, building_detail_id, combo_building_id, user_id, place_meet) VALUES ( null, true, '2022-03-08', false, '2022-03-14', 130000000, 1, 2, 1, null);
INSERT INTO request_contract (date_meet, pay_status, request_date, status, timeout_date, total_price, building_detail_id, combo_building_id, user_id, place_meet) VALUES ('2023-12-28', true, '2023-12-25', true, '2024-01-01', 100000000, 2, 3, 2, 'Nha toi');
INSERT INTO request_contract (date_meet, pay_status, request_date, status, timeout_date, total_price, building_detail_id, combo_building_id, user_id, place_meet) VALUES ('2023-06-04', true, '2023-06-01', true, '2023-06-08', 1000002000, 3, 9, 2, 'Chua 2 tang');
INSERT INTO request_contract (date_meet, pay_status, request_date, status, timeout_date, total_price, building_detail_id, combo_building_id, user_id, place_meet) VALUES (null, false, '2024-03-22', false, '2024-03-28', 19900000000, 4, 2, 4, null);
INSERT INTO request_contract (date_meet, pay_status, request_date, status, timeout_date, total_price, building_detail_id, combo_building_id, user_id, place_meet) VALUES ('2022-07-09', true, '2022-07-06', true, '2022-07-13', 1200000000, 5, 4, 5, 'Nha to');
INSERT INTO request_contract (date_meet, pay_status, request_date, status, timeout_date, total_price, building_detail_id, combo_building_id, user_id, place_meet) VALUES ('2023-08-31', true, '2023-08-28', true, '2023-09-04', 3300000000, 6, 6, 3, 'Nha chung ta');
INSERT INTO request_contract (date_meet, pay_status, request_date, status, timeout_date, total_price, building_detail_id, combo_building_id, user_id, place_meet) VALUES ('2024-02-20', true, '2024-02-16', true, '2024-02-23', 1040000000, 7, 7, 6, 'Nha minh');



-- invoice
INSERT INTO invoice (amount, invoice_id, pay_date, user_id, bank_code, bank_tran_no, card_type, order_info, response_code, secure_hash, tmn_code, transaction_no, transaction_status, txn_ref, request_contract_id) VALUES (200000, 1, '2022-03-08 14:46:58.000000', 1, 'NCB', 'NCB20170829152730', 'ATM', 'hi', '00', 'hai', '4RJNZIHK', '20170829153052', '00', '23554',1);
INSERT INTO invoice (amount, invoice_id, pay_date, user_id, bank_code, bank_tran_no, card_type, order_info, response_code, secure_hash, tmn_code, transaction_no, transaction_status, txn_ref, request_contract_id) VALUES (200000, 2, '2023-12-25 19:49:27.000000', 2, 'NCB', 'NCB20170829152730', 'ATM', 'hi', '00', 'hai', '4RJNZIHK', '20170829153052', '00', '23554',2);
INSERT INTO invoice (amount, invoice_id, pay_date, user_id, bank_code, bank_tran_no, card_type, order_info, response_code, secure_hash, tmn_code, transaction_no, transaction_status, txn_ref, request_contract_id) VALUES (200000, 3, '2023-06-01 17:49:54.000000', 2, 'NCB', 'NCB20170829152730', 'ATM', 'hi', '00', 'hai', '4RJNZIHK', '20170829153052', '00', '23554',3);
INSERT INTO invoice (amount, invoice_id, pay_date, user_id, bank_code, bank_tran_no, card_type, order_info, response_code, secure_hash, tmn_code, transaction_no, transaction_status, txn_ref, request_contract_id) VALUES (200000, 4, '2024-03-22 17:50:12.000000', 4, 'NCB', 'NCB20170829152730', 'ATM', 'hi', '01', 'hai', '4RJNZIHK', '20170829153052', '01', '23554',4);
INSERT INTO invoice (amount, invoice_id, pay_date, user_id, bank_code, bank_tran_no, card_type, order_info, response_code, secure_hash, tmn_code, transaction_no, transaction_status, txn_ref, request_contract_id) VALUES (200000, 5, '2022-07-06 15:45:40.000000', 5, 'NCB', 'NCB20170829152730', 'ATM', 'hi', '00', 'hai', '4RJNZIHK', '20170829153052', '00', '23554',5);
INSERT INTO invoice (amount, invoice_id, pay_date, user_id, bank_code, bank_tran_no, card_type, order_info, response_code, secure_hash, tmn_code, transaction_no, transaction_status, txn_ref, request_contract_id) VALUES (200000, 6, '2023-08-28 17:50:58.000000', 3, 'NCB', 'NCB20170829152730', 'ATM', 'hi', '00', 'hai', '4RJNZIHK', '20170829153052', '00', '23554',6);
INSERT INTO invoice (amount, invoice_id, pay_date, user_id, bank_code, bank_tran_no, card_type, order_info, response_code, secure_hash, tmn_code, transaction_no, transaction_status, txn_ref, request_contract_id) VALUES (200000, 7, '2024-02-16 17:51:11.000000', 6, 'NCB', 'NCB20170829152730', 'ATM', 'hi', '00', 'hai', '4RJNZIHK', '20170829153052', '00', '23554',7);

